Updated sources to bibtex handles
PhilippVerpoort/posted pull request #1
Opened 2023-11-23 14:33 UTC by gmax-L

Changed name and location of references.bib to inst/extdata/database/sources.bib
Added new sources to sources.bib
Minor corrections to the files in inst/extdata/database/teds/Tech
Changed all entries in "source" for the files in inst/extdata/database/teds/Tech to the respective bibtex handles

2023-11-27 11:18 UTC, PhilippVerpoort requested changes

2023-11-27 11:18 UTC, PhilippVerpoort commented on .DS_Store
Ich glaube, diese Datei war ein Versehen. Könntest du die vorm Merge noch rauswerfen?

2023-11-27 11:18 UTC, PhilippVerpoort commented on inst/extdata/database/sources.bib
> +	title = {Iron and Steel CCS Study (Techno-Economics Integrated Steel Mill},
Hier ist noch ein kleiner Typo (fehlende geschlossene Klammer).

2023-11-29 17:06 UTC, PhilippVerpoort requested changes

2023-11-29 17:06 UTC, PhilippVerpoort commented on inst/extdata/database/flow_types.csv
Sorry, just realising one more thing: was there a reason why you removed the unit variant from the default unit in `flow_types.csv`?

2023-11-29 17:24 UTC, LeoHeidweiler commented on inst/extdata/database/flow_types.csv
My program for viewing tables wrongly interpreted the ; in the unit as a separator, which made the table look like it had mistakes in it. I didn't realize the underlying problem and tried to correct the error. Thanks for the note, I have now reverted the change and restored the file to its original form

2023-11-30 12:42 UTC, PhilippVerpoort approved these changes

2023-11-30 12:42 UTC, PhilippVerpoort commented on inst/extdata/database/flow_types.csv
Perfect, thanks!

2023-11-30 12:44 UTC, PhilippVerpoort commented
Please go ahead with the merge!

I prefer using rebase or squash to keep the history clean.

2023-11-30 12:51 UTC, PhilippVerpoort commented
(Maybe a squash with description copied from individual commits would be preferable, also given the back-and-forth with some of the accidental changes.)

2023-12-01 14:53 UTC, merged